### ISSUE TITLE
Healing

### ISSUE THREAD

**Issue by IronsideGaming19** [HumanTree92/esx_advancedhospital#2]
When you pay to heal it removes tattoos

**Comment by HumanTree92** [comment]
There is no way. If so then there is something wrong with your tattoo script. The healing of a ped uses `SetEntityHealth`. And if the hospital script is causing the tattoos to go away then the esx_ambulancejob would do the same thing as is uses `SetEntityHealth` as well.

**Comment by HumanTree92** [comment]
My guess is ur using esx_tattooshop. If u have looked through it's closed topics u will see that it is definitely the script that has problems.
