### ISSUE TITLE
Surgery problems

### ISSUE THREAD

**Issue by xBrunex** [HumanTree92/esx_advancedhospital#3]
**Describe the Bug | A Clear & Concise Description of Bug**

The healing is working great, but when i go to Surgery it changes the stuff i want but it gives me this error in F8:

![image](https://user-images.githubusercontent.com/68948623/90340394-c4ca6e00-dfef-11ea-8187-c1edce0da9c3.png)

Maybe because it does't show me the menu like the healing ?

talking about this:
![image](https://user-images.githubusercontent.com/68948623/90340452-2985c880-dff0-11ea-919d-acab5ef7797a.png)

How can i fix that ?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): Sim, 1.2
Are you using Essentialmode?: No
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by Nikwitz** [comment]
Which version of Artifact are you using?

**Comment by xBrunex** [comment]
where can i check that mate ?

**Comment by HumanTree92** [comment]
I have tested this myself and not a single problem. I would say update to ESX V1 Final and try that.

**Comment by therealnoskill** [comment]
my Problem ist that i can surgery use for free. pick one option for example beard and can abort this action. i have still a beard.. so its a broken function -Unfortunately.-
